openapi: 3.0.3
info:
  contact:
    name: Name
    url: https://www.url.com
    email: m@il.com
  version: 0.1.0
  title: Title
externalDocs:
  description: Description
  url: https://url.com
servers:
  - url: /
    description: Description
tags:
  - name: timeseries
    description: Tameseries
paths:
  /health:
    get:
      summary: Return healthcheck.
      operationId: endpoints.healthcheck.health
      responses:
        '200':
          description: Service healthcheck result
          content:
            application/health+json:
              schema:
                description: Healthcheck endpoint result
                type: object
                required:
                  - status
                properties:
                  status:
                    type: string
                    example: 'pass'
  /api_service:
    post:
      summary: Storing data from customer.
      operationId: endpoints.timeseries_data.api_service_post
      requestBody:
        required: true
        description: List of objects to store
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  t:
                    type: integer
                  v:
                    type: number
      responses:
        '200':
          $ref: '#/components/responses/200_ok_post'
# TODO 400 and 404


  /api_service/{data_point_name}:
    get:
      operationId: endpoints.timeseries_data.api_service_get_data
      parameters:
        - in: path
          name: data_point_name
          required: true
          allowEmptyValue: false
          schema:
            type: string
          description: data point name
          example: example1
        - in: query
          name: from
          schema:
            type: integer
        - in: query
          name: to
          schema:
            type: integer
      responses:
        '200':
          $ref: '#/components/responses/200_ok_get'
# TODO 400 and 404

components:
  responses:
    200_ok_post:
      description: Average calues od data point name success - OK
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
    200_ok_get:
      description: Average calues od data point name success - OK
      headers:
        Content-Type:
          $ref: '#/components/headers/Content-Type'
      content:
        application/json:
          schema:
            type: object
            properties:
              avg:
                type: number
              sum:
                type: integer
# TODO 400 and 404
  headers:
    Content-Type:
      description: Content-Type header
      schema:
        type: string
        default: 'application/json;charset=UTF-8'